kind: Deployment
apiVersion: apps/v1
metadata:
  name: gozero-bookstore
  namespace: gozero
  labels:
    app: gozero-bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gozero-bookstore
  template:
    metadata:
      labels:
        app: gozero-bookstore
    spec:
      volumes:
        - name: bookstore-config
          configMap:
            name: bookstore-config
            defaultMode: 420
      containers:
        - name: gozero-bookstore
          image: 'gozero-bookstore:latest'
          command:
            - zero-bookstore
            - '--f=/opt/config/bookstore-api.yaml'
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: bookstore-config
              mountPath: /opt/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
