kind: Deployment
apiVersion: apps/v1
metadata:
  name: gozero-add
  namespace: gozero
  labels:
    app: gozero-add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gozero-add
  template:
    metadata:
      labels:
        app: gozero-add
    spec:
      volumes:
        - name: add-config
          configMap:
            name: add-config
            defaultMode: 420
      containers:
        - name: gozero-add
          image: 'gozero-add:latest'
          command:
            - zero-add
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: add-config
              mountPath: /etc/add.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
