apiVersion: v1
data:
  bookstore-api.yaml: |-
    Name: bookstore-api
    Host: 0.0.0.0
    Port: 8888

    Add:
      Etcd:
        Hosts:
          - 10.9.47.11:23549
        Key: add.rpc
    Check:
      Etcd:
        Hosts:
          - 10.9.47.11:23549
        Key: check.rpc
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-25T08:05:29Z"
  name: bookstore-config
  namespace: gozero
  resourceVersion: "288129146"
  uid: 39c61e0c-7740-11eb-8847-005056810c7c
